### File: [`robotis_controller_msgs/JointCtrlModule.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-Framework-msgs/blob/master/robotis_controller_msgs/msg/JointCtrlModule.msg)

### Message Definition
```
string[] joint_name
string[] module_name
```

### Description
 The message designates motion modules that controls specific joints.

* `joint_name`
&emsp;&emsp; Name of the joints to be designated with motion modules.

* `module_name`
&emsp;&emsp; Name of the motion module to control each joint.
