### File: [`thormang3_offset_tuner_msgs/JointTorqueOnOff.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-Tools/blob/master/thormang3_offset_tuner_msgs/msg/JointTorqueOnOff.msg)

### Message Definition
```
string  joint_name
bool    torque_enable
```

### Description
The message used to create [JointTorqueOnOffArray.msg](JointTorqueOnOffArray.msg)
* `string  joint_name`
&emsp;&emsp; joint name
* `bool    torque_enable`
&emsp;&emsp; true for torque on, false for torque off

<br>
[[&lt;&lt; Back|thormang3_offset_tuner_msgs]]
