### File: [`op3_online_walking_module_msgs/Step2DArray.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/develop/op3_online_walking_module_msgs/msg/Step2DArray.msg)

### Message Definition
```
float64 step_time
Step2D[] footsteps_2d
```

### Description

* `step_time`
&emsp;&emsp; movement time per one step
* `footsteps_2d`
&emsp;&emsp; foot step data

<br>
[[&lt;&lt; Back|op3_online_walking_module_msgs]]
