### File: [`op3_offset_tuner_msgs/JointTorqueOnOff.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/master/op3_offset_tuner_msgs/msg/JointTorqueOnOff.msg)
### Message Definition
```
string  joint_name
bool    torque_enable
```

### Description
The message used to create [JointTorqueOnOffArray.msg](op3_JointTorqueOnOffArray.msg)
* `string  joint_name`
&emsp;&emsp; joint name
* `bool    torque_enable`
&emsp;&emsp; true for torque on, false for torque off

[&lt;&lt; Back](op3_offset_tuner_msgs)
