### File: [`op3_walking_module_msgs/GetPreviewMatrix.srv`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/develop/op3_online_walking_module_msgs/srv/GetPreviewMatrix.srv)

### Message Definition
```
op3_online_walking_module_msgs/PreviewRequest req
---
op3_online_walking_module_msgs/PreviewResponse res
```

### Description
This service acquires parameters that are applied on op3_online_walking_module.

#### Request
* `PreviewRequest req`([op3_walking_module_msgs/PreviewRequest](op3_PreviewRequest.msg))
&emsp;&emsp; For details, refer to [PreviewRequest.msg](op3_PreviewRequest.msg).

#### Response
* `PreviewResponse res`([op3_walking_module_msgs/PreviewResponse](op3_PreviewResponse.msg))
&emsp;&emsp; For details, refer to [PreviewResponse.msg](op3_PreviewResponse.msg).

<br>[[&lt;&lt; Back|op3_online_walking_module_msgs]]
