### File: [`op3_online_walking_module_msgs/WalkingParam.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/develop/op3_online_walking_module_msgs/msg/WalkingParam.msg)

### Message Definition
```
float64 dsp_ratio
float64 lipm_height
float64 foot_height_max
float64 zmp_offset_x
float64 zmp_offset_y
```

### Description

* `dsp_ratio`
&emsp;&emsp; double support phase ratio
* `lipm_height`
&emsp;&emsp; linear inverted pendulum height
* `foot_height_max`
&emsp;&emsp; maximum value of foot height
* `zmp_offset_x`
&emsp;&emsp; ZMP offset for x-direction
* `zmp_offset_y`
&emsp;&emsp; ZMP offset for y-direction

<br>
[[&lt;&lt; Back|op3_online_walking_module_msgs]]
