### File: [`op3_online_walking_module_msgs/PreviewRequest.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/develop/op3_online_walking_module_msgs/msg/PreviewRequest.msg)

### Message Definition
```
float64 control_cycle
float64 lipm_height
```

### Description

* `control_cycle`
&emsp;&emsp; control cycle per one loop
* `lipm_height`
&emsp;&emsp; linear inverted pendulum length

<br>
[[&lt;&lt; Back|op3_online_walking_module_msgs]]
