### File: [`op3_offset_tuner_msgs/JointTorqueOnOffArray.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/master/op3_offset_tuner_msgs/msg/JointTorqueOnOffArray.msg)

### Message Definition
```
JointTorqueOnOff[] torque_enable_data
```

### Description
The message to turn on/off the torque of each joint

* `JointTorqueOnOff[] torque_enable_data`([op3_offset_tuner_msgs/JointTorqueOnOff](op3_JointTorqueOnOff.msg))
&emsp;&emsp; Array data of the joint to enable/disable torque


[&lt;&lt; Back](op3_offset_tuner_msgs)
