### File: [`op3_online_walking_module_msgs/PreviewResponse.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/develop/op3_online_walking_module_msgs/msg/PreviewResponse.msg)

### Message Definition
```
int32 K_row
int32 K_col
float64[] K
int32 P_row
int32 P_col
float64[] P
```

### Description

[Riccati Equation's solution](https://help.scilab.org/doc/5.5.2/en_US/riccati.html)

* `K_row`
&emsp;&emsp; Riccati Equation's solution K's row value
* `K_col`
&emsp;&emsp; Riccati Equation's solution K's column value
* `K`
&emsp;&emsp; Riccati Equation's solution K
* `P_row`
&emsp;&emsp; Riccati Equation's solution P's row value
* `P_col`
&emsp;&emsp; Riccati Equation's solution P's column value
* `P`
&emsp;&emsp; Riccati Equation's solution P

<br>
[[&lt;&lt; Back|op3_online_walking_module_msgs]]
