- File: [`op3_walking_module_msgs/SetWalkingParam.srv`](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-msgs/blob/master/op3_walking_module_msgs/srv/SetWalkingParam.srv)

- Message Definition
 ```
 WalkingParam        parameters
 ---
 bool                result
 ```

- Description
This service configures parameters in `op3_walking_module` for walking control.

  - Request
* `WalkingParam parameters`([op3_walking_module_msgs/WalkingParam](op3_WalkingParam.msg))
&emsp;&emsp; Walking paramters to be applied on `op3_walking_module`. For details, refer to [WalkingParam.msg](op3_WalkingParam.msg).

  - Response
* `bool result`
&emsp;&emsp;

<br>[[&lt;&lt; Back | op3_walking_module_msgs]]
