- File: [`thormang3_action_module_msgs/StartAction.msg`](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-MPC/blob/master/thormang3_action_module_msgs/msg/StartAction.msg)

- Message Definition
 ```
 int32     page_num
 string[]  joint_name_array
 ```

- Description
The message that contain a page number will be played and specified joints name will be applied action plaing result

* ` int32 page_num`
&emsp;&emsp; A page number will be played.
* `  string[] joint_name_array`
&emsp;&emsp; Specified joints names.

<br>
[[&lt;&lt; Back|thormang3_action_module_msgs]]
